# Não altere o nome da fila1 
# Use -1 para filas sem limite
# Use o nome saida para saidas sem destino de outra fila
#
# Nas saidas a ordem é feita pela sequencia que foi adicionada Ex:
# fila1.saidas: nome = fila3 e probabilidade = 0.2 , nome = fila2 e probabilidade = 0.8, neste caso 
# a probabilidade de ir para fila3 é x, sendo 0.0 <= x <= 0.2
# e a probabilidade de ir para fila2 é y, sendo 0.2 < y <= 1.0
# por um desenho seria algo como: 0.0__0.2_________1.0
# a ideia é que se o numero for 0.3 a saida sera fila2 e se for 0.15 a saida sera fila3

configuracoes:
  inicial: 2.0
  chegada0: 2.0
  chegada1: 4.0

filas:
  - nome: fila1 # não alterar nome
    tamFila: -1
    tamServ: 1
    atendimento0: 1.0
    atendimento1: 2.0
    saidas: 
    - nome: fila3
      prob: 0.2
    - nome: fila2
      prob: 0.8
    
    
  - nome: fila2
    tamFila: 5
    tamServ: 2
    atendimento0: 4.0
    atendimento1: 8.0
    saidas: 
    - nome: fila1
      prob: 0.3
    - nome: fila3
      prob: 0.5
    - nome: saida
      prob: 0.2

  - nome: fila3
    tamFila: 10
    tamServ: 2
    atendimento0: 5.0
    atendimento1: 15.0
    saidas: 
    - nome: fila2
      prob: 0.7
    - nome: saida
      prob: 0.3
